add_lunch_combo grouse-userdebug
add_lunch_combo grouse-user

add_lunch_combo grousepck-userdebug
add_lunch_combo grousepck-user

add_lunch_combo grouse_dd-userdebug
add_lunch_combo grouse_dd-user

add_lunch_combo grouse_ms12d-userdebug
add_lunch_combo grouse_ms12d-user
